### ISSUE TITLE
Failing to grab frame on basic.py

### ISSUE THREAD

**Issue by roshambo919** [doleron/raspberry-as-gige-camera#8]
![rpi-gige-debug](https://user-images.githubusercontent.com/20426598/226216063-8d360051-5679-491d-a534-f1a09131c8a4.png)

Hi! Getting started with this repository. It looks great. 

Trying to get it running on a raspberry pi 4 that runs 64 bit Bullseye OS, but running into this error. Seems it failed to grab the frame. Can you advise on this? Thanks.

**Comment by doleron** [comment]
Hi. The message says that something is wrong when OpenCV try to use gstreamer to grab images from the camera. 
- Is the alice node actually an RPI?
- Are you able to grab images on alice using plain python?
- Maybe it is a simple permission issue. Can you give a try and run `./rpiasgige -port=4001-device=/dev/video0` using `sudo`?

**Comment by roshambo919** [comment]
Thanks for the reply! Yes, it is an RPI. I am able to grab images using the picamera2 library. Running sudo did not work.

I tried `./simple_opencv_app` to no avail either. It does suggest that it's an opencv issue. I'll keep digging.

**Comment by roshambo919** [comment]
I installed OpenCV 4.5.2 from source. Is there potential for version incompatibility?
