### ISSUE TITLE
The WebSocket handshake Connection field is missing the upgrade token

### ISSUE THREAD

**Issue by c-dasq** [doleron/raspberry-as-gige-camera#9]
I get this error every time I try to connect remotely to the camera:
Error: The WebSocket handshake Connection field is missing the upgrade token

The camera is connected and available, as I can see using:
v4l2-ctl --list-devices

And I am connected to my Raspberry Pi using SSH; do you have any advice for me? thank you very much.

![image](https://user-images.githubusercontent.com/13774380/235791666-dddd3b55-81ed-4dce-ba25-806d5bf5d27c.png)

**Comment by doleron** [comment]
can you provide more details about your client? Are you using one of the client examples to connect?

**Comment by c-dasq** [comment]
I'm using pylon Viewer from Basler:

![image](https://user-images.githubusercontent.com/13774380/235801579-145b4815-ecd0-474d-a867-674fe0dd0e93.png)

I also tried to connect using pylon from python; thanks.

**Comment by doleron** [comment]
Please see here: https://github.com/doleron/raspberry-as-gige-camera/blob/main/docs/python3_client_tutorial.md
